### PR TITLE
Attack system

### LINKED ISSUE #24: Attack system
Bullets, health, hitting

### PR DESCRIPTION
**Pull request by p-98**
Introduces the health system using a HealthController, which is similar to an ActiveRemoteValue. When an enemy has no health left it gets deleted.

The bullet is realised as an entity and attacks an enemy upon collision.

Add functions for creating/deleting entities to server GameState. Currently this is done on the object-level and needs future refactoring.

Minor technical changes:
- Vector 1 and 0
- Rect helper functions

This pr introduces only minimal architectural changes. A refactoring pr is planned as follow-up to keep changes within reasonable limits.

Resolves #24
Relates to #29 (implements the technical side, but are not respected by player movement)

### CODE REVIEW

**Review by JulesOxe — COMMENTED** [review]
I just tested the functionality. I noticed a small bug: When I hold down the mouse, bullets first appear in an irregular pattern until a regular pattern suddenly appears. If you then let go of the mouse, 3-4 more bullets appear. That's not so bad, but once you've done it once, there's a very long delay between clicking the mouse and a bullet appearing :(

**Comment by p-98** [comment]
> I just tested the functionality. I noticed a small bug: When I hold down the mouse, bullets first appear in an irregular pattern until a regular pattern suddenly appears. If you then let go of the mouse, 3-4 more bullets appear. That's not so bad, but once you've done it once, there's a very long delay between clicking the mouse and a bullet appearing :(

Jan and me were both not able to reproduce your issue. There was a problem with bullet rendering but it turned out to be caused by wrong extrapolation and should now be fixed.

**Comment by p-98** [comment]
Pr is expanded by position markers which can be set from the server and are rendered on all clients.

**Comment by p-98** [comment]
Now actual bullet texture is used.

**Review by weiserhase — APPROVED** [review]
As we discussed in person, this looks good.

**Pull request merged**
